import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { getCurrentUser } from '@/lib/auth'
import { generateInvoiceNumber } from '@/lib/invoice-number'

// GET /api/invoices - List all invoices
export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')
    const clientId = searchParams.get('clientId')

    const invoices = await prisma.invoice.findMany({
      where: {
        client: {
          companyId: user.companyId,
          ...(user.branchId && { branchId: user.branchId }),
          ...(clientId && { id: clientId }),
        },
        ...(status && { status }),
      },
      include: {
        client: {
          select: {
            id: true,
            name: true,
            billingEmail: true,
          },
        },
        _count: {
          select: {
            lineItems: true,
          },
        },
      },
      orderBy: {
        issueDate: 'desc',
      },
    })

    return NextResponse.json(invoices)
  } catch (error) {
    console.error('Error fetching invoices:', error)
    return NextResponse.json(
      { error: 'Failed to fetch invoices' },
      { status: 500 }
    )
  }
}

interface LineItemInput {
  description: string
  quantity: number | string
  unitPrice: number | string
  serviceAgreementId?: string | null
  sortOrder?: number
}

// POST /api/invoices — create an invoice (status 'draft' by default).
// Required: clientId, lineItems[] with at least one item. dueDate is required
// unless the client has paymentTerms set (then we derive net N days from issueDate).
// issueDate defaults to today. invoiceNumber auto-generated by generateInvoiceNumber().
// Sending the invoice is a SEPARATE action — this endpoint only creates the record.
export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json().catch(() => ({}))
    const {
      clientId,
      lineItems,
      issueDate,
      dueDate,
      taxAmount,
      notes,
      terms,
    } = body

    if (!clientId || typeof clientId !== 'string') {
      return NextResponse.json({ error: 'clientId is required' }, { status: 400 })
    }
    if (!Array.isArray(lineItems) || lineItems.length === 0) {
      return NextResponse.json(
        { error: 'lineItems is required (at least one item)' },
        { status: 400 }
      )
    }

    // Verify the client belongs to this user's company.
    const client = await prisma.client.findFirst({
      where: {
        id: clientId,
        companyId: user.companyId,
        deletedAt: null,
      },
      select: { id: true, paymentTerms: true },
    })
    if (!client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 })
    }

    // Normalize line items and compute amounts.
    const normalizedItems = (lineItems as LineItemInput[]).map((item, idx) => {
      const description = String(item.description ?? '').trim()
      const quantity = parseFloat(String(item.quantity ?? 1))
      const unitPrice = parseFloat(String(item.unitPrice ?? 0))
      if (!description) throw new Error(`Line item ${idx + 1}: description is required`)
      if (!Number.isFinite(quantity) || quantity <= 0) {
        throw new Error(`Line item ${idx + 1}: quantity must be a positive number`)
      }
      if (!Number.isFinite(unitPrice) || unitPrice < 0) {
        throw new Error(`Line item ${idx + 1}: unitPrice must be a non-negative number`)
      }
      const amount = quantity * unitPrice
      return {
        description,
        quantity,
        unitPrice,
        amount,
        serviceAgreementId:
          typeof item.serviceAgreementId === 'string' ? item.serviceAgreementId : null,
        sortOrder: typeof item.sortOrder === 'number' ? item.sortOrder : idx,
      }
    })

    const subtotal = normalizedItems.reduce((sum, it) => sum + it.amount, 0)
    const tax = Number.isFinite(parseFloat(String(taxAmount))) ? parseFloat(String(taxAmount)) : 0
    const totalAmount = subtotal + tax

    // Dates — issueDate defaults to today; dueDate either provided or derived
    // from the client's paymentTerms (NET_15, NET_30, DUE_ON_RECEIPT).
    const issueDateValue = issueDate ? new Date(issueDate) : new Date()
    let dueDateValue: Date
    if (dueDate) {
      dueDateValue = new Date(dueDate)
    } else {
      const netDays =
        client.paymentTerms === 'NET_15'
          ? 15
          : client.paymentTerms === 'DUE_ON_RECEIPT'
            ? 0
            : 30 // default NET_30
      dueDateValue = new Date(issueDateValue.getTime() + netDays * 24 * 60 * 60 * 1000)
    }

    const invoiceNumber = await generateInvoiceNumber()

    const invoice = await prisma.invoice.create({
      data: {
        clientId,
        invoiceNumber,
        status: 'draft',
        issueDate: issueDateValue,
        dueDate: dueDateValue,
        subtotal,
        taxAmount: tax,
        totalAmount,
        amountPaid: 0,
        balanceDue: totalAmount,
        notes: typeof notes === 'string' ? notes : null,
        terms: typeof terms === 'string' ? terms : null,
        lineItems: {
          create: normalizedItems,
        },
      },
      include: {
        client: { select: { id: true, name: true, billingEmail: true } },
        lineItems: true,
      },
    })

    return NextResponse.json(invoice, { status: 201 })
  } catch (error: any) {
    console.error('Error creating invoice:', error)
    // Surface known validation errors plainly; unknown errors get the generic 500.
    if (error?.message?.startsWith('Line item')) {
      return NextResponse.json({ error: error.message }, { status: 400 })
    }
    return NextResponse.json(
      { error: 'Failed to create invoice' },
      { status: 500 }
    )
  }
}
